# Generated by Django 2.0 on 2018-10-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': '1. Categoy',
            },
        ),
        migrations.CreateModel(
            name='Galeria_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='imagen de 1000x673', upload_to='index/producto')),
            ],
            options={
                'verbose_name_plural': '3. Galery_Prodcut',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, max_length=400, null=True)),
                ('portada', models.ImageField(help_text='imagen de 1920x1292', upload_to='index/producto')),
                ('image_muestra', models.ImageField(help_text='imagen de 500x500', upload_to='index/producto')),
                ('marca', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTO.Categoria')),
            ],
            options={
                'verbose_name_plural': '2. Product',
            },
        ),
        migrations.AddField(
            model_name='galeria_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTO.Producto'),
        ),
    ]
