# Generated by Django 2.0 on 2018-10-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria_producto',
            name='foto',
            field=models.ImageField(help_text='imagen de 800x650', upload_to='index/producto'),
        ),
    ]
