# Generated by Django 2.0 on 2018-10-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRODUCTO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFiltro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de 800x514', upload_to='index/portalio')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen_slider', models.ImageField(blank=True, help_text='Imagen de 1000x673', null=True, upload_to='index/portalio')),
            ],
        ),
        migrations.CreateModel(
            name='Galery_Proyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Imagen de 800x650', upload_to='index/proyecto')),
            ],
            options={
                'verbose_name_plural': '2. Galery Project',
            },
        ),
        migrations.CreateModel(
            name='ImagenFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de 900x900', upload_to='index/portalio')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PRODUCTO.Categoria')),
            ],
            options={
                'verbose_name_plural': '1. Project',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=200)),
                ('filtro', models.CharField(blank=True, choices=[('*', 'Todas'), ('.web', 'Sala'), ('.advertising', 'cocina'), ('.branding', 'Dormitorio'), ('.design', 'Baño'), ('.photography', 'Comedor')], max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutaVideo', models.FileField(upload_to='video/proyectos')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': '4. Galery video Project',
            },
        ),
        migrations.AddField(
            model_name='galery_proyect',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PORTAFOLIO.ImagenFilter'),
        ),
    ]
