# Generated by Django 2.0 on 2018-10-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='imagen de 1200*752', upload_to='index/blog')),
                ('date', models.DateField()),
                ('title', models.TextField()),
                ('article', models.TextField()),
                ('author', models.TextField()),
                ('image2', models.ImageField(help_text='Imagen de 900x650', upload_to='index/blog')),
                ('status', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '2. blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOG.Blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BLOG.Category'),
        ),
    ]
