# Generated by Django 2.0 on 2018-10-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0002_auto_20181010_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
