# Generated by Django 2.0 on 2018-10-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0003_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.IntegerField(default=1)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BLOG.Blog', unique=True)),
            ],
            options={
                'verbose_name_plural': '3. Visits in Blog',
            },
        ),
    ]
