# Generated by Django 2.0 on 2018-10-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0004_visits_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
