# Generated by Django 2.0 on 2018-10-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0006_auto_20181012_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas_blog',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BLOG.Blog'),
        ),
    ]
