# Generated by Django 2.0 on 2018-10-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de 900x650', upload_to='index/blog')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(choices=[('icon-desktop', 'icon-desktop'), ('icon-desktop', 'icon-desktop'), ('icon-desktop', 'icon-desktop')], max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('parrafo', models.TextField()),
            ],
            options={
                'verbose_name_plural': '2. Box Item',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de 960x683', upload_to='index/features')),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '3. Feature ',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Imagen de 113x28', upload_to='index/Logo')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': '6. Footer',
            },
        ),
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de 800x650', upload_to='index/works')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '4. Recent Work ',
            },
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(choices=[('fab fa-facebook-f', 'facebook'), ('fab fa-twitter', 'twitter'), ('fab fa-google-plus-g', 'google-plus'), ('fab fa-instagram', 'instagram')], max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '5. Social networks ',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de 900x900', upload_to='index/slider')),
                ('status', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
    ]
