# Generated by Django 2.0 on 2018-10-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRINCIPAL', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': '4. Footer'},
        ),
        migrations.AlterModelOptions(
            name='recentwork',
            options={},
        ),
    ]
