# Generated by Django 2.0 on 2018-10-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRINCIPAL', '0002_auto_20181010_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxitem',
            name='icono',
            field=models.ImageField(help_text='Imagen de 60x60', upload_to='index/icon'),
        ),
    ]
