# Generated by Django 2.0 on 2018-10-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRINCIPAL', '0006_auto_20181024_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redessociales',
            name='icono',
            field=models.CharField(choices=[('fa fa-facebook-f', 'facebook'), ('fa fa-user', 'user'), ('fa fa-google-plus-g', 'google-plus'), ('fa fa-instagram', 'instagram')], max_length=100),
        ),
    ]
