# Generated by Django 2.0 on 2018-10-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRINCIPAL', '0007_auto_20181024_1701'),
        ('PRINCIPAL', '0008_auto_20181024_1714'),
    ]

    operations = [
    ]
