# Generated by Django 2.0 on 2018-10-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPRESA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
