# Generated by Django 2.0 on 2018-10-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMPRESA', '0002_contact_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': '2. Company'},
        ),
        migrations.AlterModelOptions(
            name='companylogo',
            options={'verbose_name_plural': '3. Company logo'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '5. Contact'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name_plural': '4. Provider'},
        ),
        migrations.AlterModelOptions(
            name='seccionfoto',
            options={},
        ),
    ]
