# Generated by Django 2.0 on 2018-10-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPRESA', '0003_auto_20181010_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='paragraph_about',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='title_about',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seccionfoto',
            name='parrafo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='image_3',
            field=models.ImageField(help_text='Imagen de 2500x730', upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title_1',
            field=models.CharField(blank=True, default='Objetive', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='title_2',
            field=models.CharField(blank=True, default='Mission', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='title_3',
            field=models.CharField(blank=True, default='View', max_length=100, null=True),
        ),
    ]
