# Generated by Django 2.0 on 2018-10-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPRESA', '0004_auto_20181011_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
