# Generated by Django 2.0 on 2018-10-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPRESA', '0005_formulario_formulariocontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='paragraph_about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
